# Generated by Django 5.1.7 on 2025-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_unitofmeasurement_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('unidade', 'Unidade'), ('kg', 'Kilograma'), ('m', 'Metro'), ('l', 'Litro')], max_length=50, null=True, verbose_name='Un. de Medida'),
        ),
        migrations.DeleteModel(
            name='UnitOfMeasurement',
        ),
    ]
