# Generated by Django 5.1.7 on 2025-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_unitofmeasurement_alter_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('unidade', 'Unidade'), ('par', 'Par'), ('kit', 'Kit'), ('kg', 'Kilograma'), ('g', 'Grama'), ('mg', 'Miligrama'), ('km', 'Kilômetro'), ('m', 'Metro'), ('cm', 'centímetro ')], max_length=50, null=True, verbose_name='Un. de Medida'),
        ),
        migrations.DeleteModel(
            name='UnitOfMeasurement',
        ),
    ]
