# Generated by Django 5.1.7 on 2025-03-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_unitofmeasurement_alter_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasurement',
            options={'ordering': ['name'], 'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Un. de medida'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Símbolo'),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
